<?php

namespace AppBundle\Repository;


/**
 * PonenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PonenteRepository extends \Doctrine\ORM\EntityRepository
{

    public function getPonentesByDay()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('p, d')
            ->from('AppBundle:Ponente', 'p')
            ->join("p.day", "d");
        return $qb->getQuery()->getArrayResult();
    }

}
